// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: paymentsapi.proto

package api

import (
	context "context"

	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentsApi_UpdatePaymentStatus_FullMethodName = "/paymentsapi.PaymentsApi/UpdatePaymentStatus"
	PaymentsApi_GetPing_FullMethodName             = "/paymentsapi.PaymentsApi/GetPing"
)

// PaymentsApiClient is the client API for PaymentsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsApiClient interface {
	UpdatePaymentStatus(ctx context.Context, in *PayStatus, opts ...grpc.CallOption) (*empty.Empty, error)
	GetPing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error)
}

type paymentsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsApiClient(cc grpc.ClientConnInterface) PaymentsApiClient {
	return &paymentsApiClient{cc}
}

func (c *paymentsApiClient) UpdatePaymentStatus(ctx context.Context, in *PayStatus, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, PaymentsApi_UpdatePaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsApiClient) GetPing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, PaymentsApi_GetPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsApiServer is the server API for PaymentsApi service.
// All implementations must embed UnimplementedPaymentsApiServer
// for forward compatibility.
type PaymentsApiServer interface {
	UpdatePaymentStatus(context.Context, *PayStatus) (*empty.Empty, error)
	GetPing(context.Context, *empty.Empty) (*Pong, error)
	mustEmbedUnimplementedPaymentsApiServer()
}

// UnimplementedPaymentsApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentsApiServer struct{}

func (UnimplementedPaymentsApiServer) UpdatePaymentStatus(context.Context, *PayStatus) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaymentStatus not implemented")
}
func (UnimplementedPaymentsApiServer) GetPing(context.Context, *empty.Empty) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPing not implemented")
}
func (UnimplementedPaymentsApiServer) mustEmbedUnimplementedPaymentsApiServer() {}
func (UnimplementedPaymentsApiServer) testEmbeddedByValue()                     {}

// UnsafePaymentsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsApiServer will
// result in compilation errors.
type UnsafePaymentsApiServer interface {
	mustEmbedUnimplementedPaymentsApiServer()
}

func RegisterPaymentsApiServer(s grpc.ServiceRegistrar, srv PaymentsApiServer) {
	// If the following call pancis, it indicates UnimplementedPaymentsApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentsApi_ServiceDesc, srv)
}

func _PaymentsApi_UpdatePaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsApiServer).UpdatePaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsApi_UpdatePaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsApiServer).UpdatePaymentStatus(ctx, req.(*PayStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsApi_GetPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsApiServer).GetPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsApi_GetPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsApiServer).GetPing(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentsApi_ServiceDesc is the grpc.ServiceDesc for PaymentsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentsapi.PaymentsApi",
	HandlerType: (*PaymentsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePaymentStatus",
			Handler:    _PaymentsApi_UpdatePaymentStatus_Handler,
		},
		{
			MethodName: "GetPing",
			Handler:    _PaymentsApi_GetPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentsapi.proto",
}
